swiftlint_version: 0.42.0
disabled_rules:
  - cyclomatic_complexity
  - force_cast
  - force_try
  - identifier_name
  - nesting
  - redundant_discardable_let
  - todo
  - type_name
  - unused_optional_binding
  - xctfail_message
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - file_header
  - multiline_parameters
  - vertical_parameter_alignment_on_call
included:
  - Sources
  - Tests
function_parameter_count:
  warning: 20
  error: 25
line_length:
  warning: 250
  error: 450
large_tuple:
  warning: 4
type_body_length:
  warning: 450
  error: 650
function_body_length: 80
file_length:
  warning: 600
  error: 1200
trailing_comma:
  mandatory_comma: true
file_header:
  required_pattern: "// Copyright © (\\d+|\\d+-\\d+) .*.\n//\n// This file is part of JdenticonSwift. The full Trust copyright notice, including\n// terms governing use, modification, and redistribution, is contained in the\n// file LICENSE at the root of the source code distribution tree."
superfluous_disable_command: warning
reporter: "xcode"
